version: "3"

services:
  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: nest-second-poc
    ports:
      - "3001:3000"
    volumes:
      - .:/home/node/app
    depends_on:
      - db

  db:
    build: .docker/postgres
    container_name: nest-second-poc-db
    restart: always
    tty: true
    env_file:
      - .env
    ports: 
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: nest-second-poc-pgadmin
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGDATA=/tmp
    ports:
      - "8000:80"
    depends_on:
      - db
    
volumes:
  pgdata:
    driver: local